### ISSUE TITLE
Promote this to DDEV namespace?

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-sqlsrv#13]
It seems like you're keeping this well-maintained. Should it be promoted to the github.com/ddev namespace as official? You'd still be the maintainer.

Also, please add to the README
* https://github.com/microsoft/mssql-docker/issues/734
* https://github.com/microsoft/mssql-docker/issues/802

**Comment by robertoperuzzo** [comment]
Yes sure, it's a honor :)

**Comment by rfay** [comment]
I invited you to https://github.com/ddevl - Just transfer the repo to there, and I'll then transfer it to github.com/ddev. 

Then you'll need to do a PR to update things, and a new release. You'll remain the maintainer (you're the one that knows what's going on!)

And please keep your eyes on the arm64 support. Someday... It probably could be made to work right now with some situations on Apple Silicon. Docker Desktop, Colima, and OrbStack all have virtualization capabilities in Ventura. It would be questionable, but interesting to explore.

**Comment by robertoperuzzo** [comment]
I transferred the repo to https://github.com/ddevl, say to me if I have to do further actions. Thanks.

**Comment by rfay** [comment]
Yay, congrats, please update all the references and thanks for maintaining it!

**Comment by tyler36** [comment]
@robertoperuzzo  Great job!
