### ISSUE TITLE
Tests (stable) are failing

### ISSUE THREAD

**Issue by robertoperuzzo** [ddev/ddev-sqlsrv#17]
Here the job's log https://github.com/ddev/ddev-sqlsrv/actions/runs/6361539233

It seems something regarding the "Branch protection rules" as discussed [here](https://github.com/orgs/community/discussions/58914#discussioncomment-6266162).

**Comment by rfay** [comment]
It looks like perhaps the main branch has been set to protected. Easing up on that might fix.

**Comment by rfay** [comment]
You may want to take a pass through the [tests.yml](https://github.com/ddev/ddev-sqlsrv/blob/main/.github/workflows/tests.yml) and update to the current setup in the template as well. The template now uses a github action for most setup. 

https://github.com/ddev/ddev-addon-template/blob/main/.github/workflows/tests.yml

**Comment by rfay** [comment]
Perhaps...

<img width="912" alt="image" src="https://github.com/ddev/ddev-sqlsrv/assets/112444/9ed8e2f5-c77d-4de8-a57e-caf491c92b5f">

**Comment by robertoperuzzo** [comment]
I suppose so, but I don't have the permission to the "Settings" menu.

By the way, I'm going to check my test.yml.

**Comment by rfay** [comment]
Now you do, you should have before.

**Comment by robertoperuzzo** [comment]
Now I see the menu! I unchecked the "Require a pull request before merging" protection.
<img width="840" alt="Screenshot_2023-09-30_at_14_58_09" src="https://github.com/ddev/ddev-sqlsrv/assets/6221210/00cb1fb3-d62c-4fb4-b50d-f4565062298d">

**Comment by rfay** [comment]
Ah, that would do it. 

If you haven't pushed anything new, you should be able to see whether you're successful tomorrow :)

**Comment by rfay** [comment]
Thanks for watching, chasing, and solving!

**Comment by rfay** [comment]
<img width="955" alt="image" src="https://github.com/ddev/ddev-sqlsrv/assets/112444/1c9c8200-4d4a-47a0-a63c-65d8744be4ff">
