### ISSUE TITLE
Automated Tests are failing

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-sqlsrv#29]
**Describe the bug**

As of today, the automated tests are failing. 

I re-ran them a couple of times, but they're failing on both HEAD and stable, so it's probably not something to do with DDEV.

I manually tried `ddev get ddev/ddev-sqlsrv` on gitpod and it worked OK, but the `ddev restart` did take forever. Maybe something has just slowed down...

**Comment by rfay** [comment]
It looks like either github or MS has changed something. It may be worth trying to try some of the newer images in https://mcr.microsoft.com/en-us/product/mssql/server/tags ?

@robertoperuzzo could you take a look at this? Debugging using tmate is covered in https://github.com/ddev/ddev-addon-template?tab=readme-ov-file#how-to-debug-tests-github-actions

**Comment by rfay** [comment]
Current runner is ubuntu-latest, which currently means 22.04, see https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md. It was in fact updated Sept 16:

* https://github.com/actions/runner-images/pull/10627

The release was just several hours ago, so this is probably the reason for the failure.

**Comment by robertoperuzzo** [comment]
Thank you @rfay for your report. I'm going to look at it in the next few days during the DrupalCon Europe.

**Comment by rfay** [comment]
Cool, thanks! We can take a look together if you need any help looking at it. Another project had trouble because of the new `docker-compose` in HEAD, but your trouble here is both stable and head, so I guess it's maybe github runner.

**Comment by rfay** [comment]
- https://github.com/microsoft/mssql-docker/issues/881

**Comment by rfay** [comment]
@robertoperuzzo and I took a look at this, and 

* Inside the Github Actions runner, you can't even do a `ddev start` because the sqlsrv process hits a SIGABRT, perhaps due to a kernel issue.
* On gitpod, `ddev start` works OK

Possible paths to figure something out:

* Try all the possible runners provided by GitHub
* Try some other versions of sqlsrv Docker images from MS

**Comment by robertoperuzzo** [comment]
@rfay  I try to use the same Ubuntu version in both the action runner's and the sqlsrv images and it seems to works https://github.com/ddev/ddev-sqlsrv/actions/runs/11052477017?pr=30
