### ISSUE TITLE
in ddev version 1.24 the plugin does not work for me

### ISSUE THREAD

**Issue by manuel-benavides** [ddev/ddev-sqlsrv#32]
In a project that was working fine with database connections in Sqlsrv, I updated the ddev version to 1.24.1 and the add-on stopped working. I have reviewed all the configuration but I always got the message could not driver found. I have returned to version of ddev 1.23.5 and everything has worked normally again.
I am working in a local environment with wsl ubuntu 22.04 and laravel

**Comment by stasadev** [comment]
Related Discord conversation: https://discord.com/channels/664580571770388500/1068592266752573440/1316758290176147537

@manuel-benavides, you'll need to provide more details to help us understand the issue, including the exact steps you're following and any error messages.

Do you have the latest add-on version `ddev add-on list --installed`? Also, have you made any custom changes to its configuration?

Try reproducing the problem by [creating a new Laravel project](https://ddev.readthedocs.io/en/stable/users/quickstart/#laravel), installing this add-on, and explaining what we need to do. (I'm not familiar with MSSQL.)

**Comment by rfay** [comment]
Also @manuel-benavides if you would be so kind as to attach the output of `ddev debug test`, and say whether you did what I suggested in Discord, (https://discord.com/channels/664580571770388500/1316758290176147537/1316775311987179595) - 
```
ddev ssh
sqlcmd -S sqlsrv -U sa -P "Password12!"
>
```

**Comment by manuel-benavides** [comment]
Hello everyone;
I have installed a project from scratch with Laravel mysql and sqlsrv and everything works correctly. I have installed everything with ddev version 1.24.
Perdon por mi ignorancia

**Comment by rfay** [comment]
Glad it worked for you!

**Comment by hockdudu** [comment]
I also had a similar issue (`could not find driver`) on a project that worked before but stopped working recently.

I debugged and found out that the `sqlsrv` and `pdo_sqlsrv` extensions were added and loaded to `/etc/php/7.0/cli/conf.d/`, but not to `/etc/php/7.0/fpm/conf.d/`. (I know that this PHP version is ancient, it's a legacy project 😅)

My solution was to create the following file at `.ddev/web-build/Dockerfile.sqlsrv`:

```Dockerfile
# The extensions isn't properly installed during the `pre.Dockerfile.*` phase,
# so we must activate it again here
RUN phpenmod -v $DDEV_PHP_VERSION sqlsrv pdo_sqlsrv
```
